#!/bin/bash
#BSUB -J Pd_111_5Layer-H
#BSUB -q q_hpc
#BSUB -n 32
#BSUB -o %J.out
#BSUB -e %J.err
#BSUB -R "span[ptile=16]"
#BSUB -B
#BSUB -N
#BSUB -u ccuan@pceim.unam.mx
#

module load tbb/2021.6.0
module load compiler-rt/2022.1.0
module load intel/2022.1.0
module load mpi/intel-2021.6.0
module load mkl/2022.1.0
module load quantum/7.3

export OMP_NUM_THREADS=1
export MKL_NUM_THREADS=1
export OMP_DYNAMIC=false
export MKL_DYNAMIC=false
export OMP_PLACES=cores
export OMP_PROC_BIND=close
export I_MPI_PIN=1
export I_MPI_PIN_DOMAIN=core
export I_MPI_FABRICS=shm:ofi
export I_MPI_DEBUG=0

mpirun -np 32 pw.x -npool 4 -ntg 2 -ndiag 4 -inp Pd_111_5Layer-H.in > Pd_111_5Layer-H.out
